default_agent: solution_architect_copilot_agentcore
agents:
  rfx_agentcore_orchestrator:
    name: rfx_agentcore_orchestrator
    entrypoint: /home/ec2-user/SageMaker/backend_backup/main.py
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: 040504913362
      region: us-east-1
      ecr_repository: 040504913362.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-rfx_agentcore_orchestrator
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: 12ef242e-660f-43b2-b344-a3b71454b82e
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: rfx_agentcore_orchestrator_mem-1C58maCqHa
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:040504913362:memory/rfx_agentcore_orchestrator_mem-1C58maCqHa
      memory_name: rfx_agentcore_orchestrator_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  solution_architect_copilot_agentcore:
    name: solution_architect_copilot_agentcore
    entrypoint: /home/ec2-user/SageMaker/backend_backup/main.py
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::040504913362:role/HCL-User-Role-Aiml-BedrockAgentCore
      execution_role_auto_create: false
      account: 040504913362
      region: us-east-1
      ecr_repository: 040504913362.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-solution_architect_copilot_agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: solution_architect_copilot_agentcore-QfX1ZG3kA6
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:040504913362:runtime/solution_architect_copilot_agentcore-QfX1ZG3kA6
      agent_session_id: 844f0ab8-24cf-4510-8cf1-9d942c451557
    codebuild:
      project_name: bedrock-agentcore-solution_architect_copilot_agentcore-builder
      execution_role: arn:aws:iam::040504913362:role/HCL-User-Role-Aiml-BedrockAgentCore-CodeBuild
      source_bucket: bedrock-agentcore-codebuild-sources-040504913362-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: solution_architect_copilot_agentcore_mem-nXn74dH6s8
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:040504913362:memory/solution_architect_copilot_agentcore_mem-nXn74dH6s8
      memory_name: solution_architect_copilot_agentcore_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
